### ISSUE TITLE
Python Script for QuattroCento Device Communication

### ISSUE THREAD

**Issue by maximilianC33** [OTBioelettronica/OTB-Python#1]
Would it be possible to get a python script for device communication with the QuattroCento written/uploaded?

**Comment by OTBioelettronica** [comment]
Hi Maximilian,
Yes of course! I'm going to upload what we currently have. The script is a little different from the others (examples read_device/communication_device) because of the high number of channels. It uses PyQt for plotting and have better performance. You can download it from Python Script/Examples.
Simone

**Comment by maximilianC33** [comment]
Thanks Simone!
